using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SqliteDna.SourceGenerator
{
    [Generator]
    public class Generator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is SyntaxReceiver receiver))
                return;

            context.AnalyzerConfigOptions.GlobalOptions.TryGetValue("build_property.PublishAOT", out string? publishAOT);

            string source = """
// <auto-generated/>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace SqliteDna.SourceGenerator
{
    public class Init
    {
        [UnmanagedCallersOnly(EntryPoint = "sqlite3_[ASSEMBLY-NAME]_init", CallConvs = new[] { typeof(CallConvCdecl) })]
        public unsafe static int sqlite3_sqlitedna_init(IntPtr db, byte** pzErrMsg, IntPtr pApi)
        {
            SqliteDna.Integration.Sqlite.Init(db, pzErrMsg, pApi);

[CREATE_FUNCTIONS]
            return SqliteDna.Integration.Sqlite.SQLITE_OK;
        }
    }

    public class Functions
    {[FUNCTIONS]
    }
}
""";
            string assemblyName = context.Compilation.AssemblyName!;
            string assemblyNameSuffix = string.Compare(publishAOT, "true", true) == 0 ? "" : "ne";
            source = source.Replace("[ASSEMBLY-NAME]", assemblyName.ToLower() + assemblyNameSuffix);

            string functions = "";
            string createFunctions = "";
            foreach (var i in receiver.Functions)
            {
                string functionBody = """

                    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
                    public static unsafe int [FUNCTION_NAME](IntPtr context, int argc, IntPtr argv)
                    {
                        IntPtr* pValues = (IntPtr*)argv;

                        SqliteDna.Integration.Sqlite.Result[RESULT_TYPE](context, [FULL_FUNCTION_NAME]());
                        return SqliteDna.Integration.Sqlite.SQLITE_OK;
                    }
                    """;
                functionBody = functionBody.Replace("[RESULT_TYPE]", AdaptType(i.ReturnType));
                functionBody = functionBody.Replace("[FUNCTION_NAME]", i.Name);
                functionBody = functionBody.Replace("[FULL_FUNCTION_NAME]", $"{i.ContainingType.ContainingNamespace}.{i.ContainingType.Name}.{i.Name}");
                functions += functionBody;
                createFunctions += $"            SqliteDna.Integration.Sqlite.CreateFunction(\"{i.Name}\", 0, &Functions.{i.Name});\r\n";
            }
            source = source.Replace("[FUNCTIONS]", functions);
            source = source.Replace("[CREATE_FUNCTIONS]", createFunctions);

            context.AddSource($"SqliteDna.Init.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        private static string AdaptType(ITypeSymbol typeSymbol)
        {
            switch (typeSymbol.SpecialType)
            {
                case SpecialType.System_SByte:
                case SpecialType.System_Int16:
                case SpecialType.System_Int32:
                case SpecialType.System_Int64:
                case SpecialType.System_Byte:
                case SpecialType.System_UInt16:
                case SpecialType.System_UInt32:
                case SpecialType.System_UInt64:
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                    return "Double";
                case SpecialType.System_String:
                    return "String";
            }

            return typeSymbol.Name;
        }

        class SyntaxReceiver : ISyntaxContextReceiver
        {
            public List<IMethodSymbol> Functions { get; } = new List<IMethodSymbol>();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is MethodDeclarationSyntax methodSyntax)
                {
                    IMethodSymbol methodSymbol = (context.SemanticModel.GetDeclaredSymbol(methodSyntax) as IMethodSymbol)!;
                    if (methodSymbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString(fullNameFormat) == "SqliteDna.Integration.FunctionAttribute"))
                        Functions.Add(methodSymbol);
                }
            }

            private static SymbolDisplayFormat fullNameFormat = new SymbolDisplayFormat(typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces);
        }
    }
}
