using Microsoft.CodeAnalysis;

namespace SqliteDna.SourceGenerator
{
    [Generator]
    public class Generator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            string source = """
// <auto-generated/>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace SqliteDna.SourceGenerator
{
    public class Init
    {
        [UnmanagedCallersOnly(EntryPoint = "sqlite3_testdnnene_init", CallConvs = new[] { typeof(CallConvCdecl) })]
        public unsafe static int sqlite3_sqlitedna_init(IntPtr db, byte** pzErrMsg, IntPtr pApi)
        {
            return 0;
        }
    }
}
""";

            context.AddSource($"SqliteDna.Init.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
        }
    }
}
